apiVersion: v1
appVersion: "1.0"
description: pgAdmin is a web based administration tool for PostgreSQL database
name: pgadmin
version: 0.1.0
home: https://www.pgadmin.org/
source: https://github.com/rowanruseler/pgadmin
maintainers:
  - name: Rowan Ruseler
    email: rowanruseler@gmail.com
