# Default values for pgadmin.

replicaCount: 1

image:
  repository: dpage/pgadmin4
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {
    certmanager.k8s.io/cluster-issuer: letsencrypt
    #    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
  }
  hosts:
    - host: pgadmin.domain.com
      paths:
        - /
  tls:
    - secretName: pgadmin-tls
      hosts:
        - pgadmin.domain.com

environment:
  username: pgadmin@domain.com
  password: SuperSecret

persistence:
  enabled: true
  annotations: {
    volume.alpha.kubernetes.io/storage-class: default
  }
  accessMode: ReadWriteOnce
  size: 10Gi

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
