{{- if .Values.persistence.enabled }}
{{- $fullName := include "pgadmin.fullname" . -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ "fullname" }}
  labels:
{{ include "pgadmin.labels" . | indent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
